name: ğŸ³ Build + Publish Multi-Platform Image

on:
  workflow_dispatch:
  push:
    branches: ['master']
    tags: ['*.*']
    paths:
      - '**.js'
      - 'src/**'
      - 'public/**'
      - 'services/**'
      - '.github/workflows/docker-build-publish.yml'
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  DH_IMAGE: ${{ secrets.DOCKER_REPO }}
  GH_IMAGE: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
    - name: ğŸ›ï¸ Checkout Repo
      uses: actions/checkout@v3

    - name: ğŸ”– Get App Version
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version

    - name: ğŸ—‚ï¸ Make Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ env.GH_IMAGE }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}},enable=false
          type=semver,pattern={{major}}.x
          type=raw,value=latest
        flavor: |
          latest=false
        labels: |
          maintainer=LaoWang
          org.opencontainers.image.title=LaoWang Nav
          org.opencontainers.image.description=Personal navigation homepage
          org.opencontainers.image.authors=tony-wang1990
          org.opencontainers.image.licenses=MIT

    - name: ğŸ”§ Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64

    - name: ğŸ”§ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx

    - name: ğŸ‘€ Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: ğŸ”‘ Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: âš’ï¸ Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
